# version: '3.8'

services:
  # 1. 웹 서버 (Nginx)
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80" # 브라우저에서 localhost:8000 으로 접속
    volumes:
      - ./src:/var/www/html # [핫리로드] 내 PC 소스 <-> 컨테이너 동기화
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  # 2. PHP (Laravel)
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html # [핫리로드] 수정 시 즉시 반영
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_HOST=redis
    ports:
      - "5173:5173" # vite 개발서버 포트 포워딩

  # 3. 데이터베이스 (MariaDB)
  db:
    image: mariadb:10.11 # LTS 버전
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql # [데이터 영구보존] 재실행해도 데이터 유지

  # 4. Redis (캐시)
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data # [데이터 영구보존]

# 볼륨 정의 (데이터 저장소 생성)
volumes:
  db_data:
  redis_data: